### ISSUE TITLE
 Invalid region in config

### ISSUE THREAD

**Issue by tmokmss** [teamplanes/cdk-watch#30]
Hi, when I run `npx cdkw "**"`, the following error occurs.

```sh
$ npx cdkw "**" 
synthesizing CDK app... done
Error [ConfigError]: Invalid region in config
    at Request.VALIDATE_REGION (/mydir/node_modules/aws-sdk/lib/event_listeners.js:97:47)
    at Request.callListeners (/mydir/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at callNextListener (/mydir/node_modules/aws-sdk/lib/sequential_executor.js:96:12)
    at /mydir/node_modules/aws-sdk/lib/event_listeners.js:86:9
    at finish (/mydir/node_modules/aws-sdk/lib/config.js:386:7)
    at /mydir/node_modules/aws-sdk/lib/config.js:404:9
    at SharedIniFileCredentials.get (/mydir/node_modules/aws-sdk/lib/credentials.js:127:7)
    at getAsyncCredentials (/mydir/node_modules/aws-sdk/lib/config.js:398:24)
    at Config.getCredentials (/mydir/node_modules/aws-sdk/lib/config.js:418:9)
    at Request.VALIDATE_CREDENTIALS (/mydir/node_modules/aws-sdk/lib/event_listeners.js:81:26) {
  code: 'ConfigError',
  time: 2021-05-23T14:27:22.590Z
}
```

I found the region for aws-sdk is set here:
https://github.com/teamplanes/cdk-watch/blob/5706e558b9a90c3e925461190316aca02c682b38/src/lib/initAwsSdk.ts#L4

And this region comes from here:
https://github.com/teamplanes/cdk-watch/blob/5706e558b9a90c3e925461190316aca02c682b38/src/commands/watch.ts#L32
https://github.com/teamplanes/cdk-watch/blob/5706e558b9a90c3e925461190316aca02c682b38/src/lib/readManifest.ts#L4-L11
https://github.com/teamplanes/cdk-watch/blob/5706e558b9a90c3e925461190316aca02c682b38/src/consts.ts#L1

So I checked `cdk.out/manifest.cdk-watch.json` and found `region` is set as a string like `${Token[AWS.Region.11]}`, instead of region names such as `us-west-1` or `ap-northeast-1`.
It appears unresolved CDK token and that's why aws-sdk regards it as an invalid region.

It worked successfully when I set a stack's region explicitly via stack property like `env: {region: 'ap-northeast-1'}`.

Great project though, thanks!

**Comment by kirkness** [comment]
Hey @tmokmss - how are you currently setting the region of your stack? Is it something like `env: {region: someOtherStack.region}`?

**Comment by tmokmss** [comment]
Hi, thanks for the reply! I leave it `undefined` e.g.: 

```ts
new CdkWatchExampleStack(app, "CdkWatchExampleStack", {});
```

I made a minimum reproducible code repo here: https://github.com/tmokmss/cdk-watch-example

**Comment by kirkness** [comment]
Woah, interesting! Cheers for raising, I'll have a look into this.

**Comment by kirkness** [comment]
Had a quick look into this and it looks as if there is no simple workaround for when the region is not specified. As a "fix" for now, I've added a check to verify the token is resolved so that at least the error is easy to determine and resolve.

Closing this for now, please let me know if this is a blocker for you.
