### ISSUE TITLE
synth command does not support `context`

### ISSUE THREAD

**Issue by hffmnn** [teamplanes/cdk-watch#6]
Hi,

our current synth setup is based on context variables when calling `cdk synth`. This does not work with cdk-watch because it looks like cdk-watch ignores those flags.

**Comment by kirkness** [comment]
Right you are! Will get a fix in for this.

*Note to self, **tests*** 😬

**Comment by kirkness** [comment]
Hey @hffmnn, I've just had a play with this, it actually looks like an issue with how I've configured `commander` because this works:
```
cdkw --profile=planes --context=hi=hello "**/MyLambda"
```

However, these don't:
```
cdkw --profile=planes -c=hi=hello "**/MyLambda"
cdkw --profile=planes -c hi=hello "**/MyLambda"
cdkw --profile=planes --context hi=hello "**/MyLambda"
```

**Comment by hffmnn** [comment]
ok, thanks a lot. will retry with your suggestions.

**Comment by kirkness** [comment]
@hffmnn this was also fixed in [this pr](https://github.com/teamplanes/cdk-watch/pull/7/files), note that the command ordering has slightly changed. i.e. you'll now do:

```
cdkw "**/MyLambda" --context hi=hello
cdkw "**/MyLambda" -c hi=hello
```
